services:
  coin:
    build:
      context: ~/IdeaProjects/pickupcoins
      dockerfile: Dockerfile-local
      args:
        - VERSION=${VERSION}
    container_name: coin
    image: coin:${VERSION}
    ports:
      - 7070:8080
    volumes:
      - /tmp/log/pickupcoins:/logs
    networks:
      - coin-network

networks:
  coin-network:
    driver: bridge
