FROM nginx:1.27-alpine
LABEL description="admin-web"

# Update packages to fix vulnerabilities
RUN apk update && apk upgrade && rm -rf /var/cache/apk/*

COPY ./admin-web/dist /usr/share/nginx/html
COPY ./admin-web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

