FROM nginx:alpine
LABEL description="admin-web"
MAINTAINER hajubal@gmail.com

COPY ./admin-web/dist /usr/share/nginx/html
COPY ./admin-web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

