FROM openjdk:17-alpine
LABEL description="admin-api"
MAINTAINER hajubal@gmail.com

ARG VERSION=2.0.0

COPY ./admin-api/build/libs/admin-api-${VERSION}.jar /admin-api.jar

RUN mkdir /logs

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/admin-api.jar", "--spring.profiles.active=dev"]

