FROM openjdk:17-alpine
LABEL description="pickup-server"
MAINTAINER hajubal@gmail.com

ARG VERSION=2.0.0

COPY ./pickup-server/build/libs/pickup-server-${VERSION}.jar /pickupcoins.jar

RUN mkdir /logs

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/pickupcoins.jar", "--spring.profiles.active=dev"]

