services:
  coin:
    build:
      context: ~/IdeaProjects/pickupcoins
      dockerfile: Dockerfile-local
      args:
        - VERSION=${VERSION}
    container_name: coin
    image: coin:${VERSION}
    restart: always
    depends_on:
      - coin-mysql
    ports:
      - 7070:8080
    volumes:
      - /tmp/log/pickupcoins:/logs
    networks:
      - coin-network

  coin-mysql:
    container_name: coin-mysql
    image: mysql:8.0
    restart: always
    hostname: coin-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_LOWER_CASE_TABLE_NAMES=1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coin-network

networks:
  coin-network:
    driver: bridge

volumes:
  mysql_data:
