spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        #print console
        #show_sql: true
        format_sql: true
        #JPQL query view
        use_sql_comments: true
logging:
  level:
    me.synology.hajubal.coins: debug
    org:
      springframework: info
      hibernate:
        #print logger
        SQL: debug
        #parameter mapping (p6spy-spring-boot-starter)
        type: trace
      apache:
        coyote:
          http11: debug