spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/coins;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa

  security:
    user:
      name: test
      password: test

logging:
  file:
    path: d:/logs

slack:
  webhook:
    url: https://hooks.slack.com/services/1/2/3

naver:
  cookie: ha:NID_AUT=186; NID_SES=AAABsmU=,
    park:NID_AUT=186; NID_SES=AAABsmU=
