spring:
  application:
    name: coin
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        #print console
#        show_sql: true
#        format_sql: true
        #JPQL query view
#        use_sql_comments: true
  messages:
    basename: messages,errors
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    me.synology.hajubal.coins: debug
    org.apache.coyote.http11: trace
    #print logger
    org.hibernate.SQL: info
    #parameter mapping
    org.hibernate.type: info

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
