spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/coins;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always

logging:
  file:
    path: /tmp/log/pickupcoins
