spring:
  application:
    name: coin
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        #print console
#        show_sql: true # true 설정 시, 콘솔에 JPA 쿼리를 보여준다.
#        format_sql: true # true 설정 시, 콘솔에 표시되는 쿼리를 가독성있게 보여준다.
        #JPQL query view
#        use_sql_comments: true # true 설정 시, 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 hint 를 보여준다.
  messages:
    basename: messages,errors
  thymeleaf:
    cache: false
  # html form method extension by spring mvc
  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoint:
    info:
      enabled: true
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  tomcat:
    mbeanregistry:
      enabled: true

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j

logging:
  level:
    root: info
    me.synology.hajubal.coins: debug
    org.apache.coyote.http11: trace

