name: Gemini On-Demand

on:
  issue_comment:
    types: [created]

jobs:
  delegate:
    if: contains(github.event.comment.body, '@gemini-cli')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: "${{ github.event.comment.body }}"
